name: code_initial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.3.3
  another_flutter_splash_screen: ^1.2.1
  pinput: ^6.0.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ordinateur.jpg
    - assets/images/blanc.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/facebook.jpg
    - assets/images/hp.jpg
    - assets/images/smartwatch.jpg
    - assets/images/téléviseur.jpg
    - assets/images/Products/produit_montre.jpg
    - assets/images/Products/Pro.jpg
    - assets/images/iphone.jpg
    - assets/images/samsung.jpg
    - assets/images/macbook.jpg
